### ISSUE TITLE
请问jeeves与itchat之间的关系大致是什么？

### ISSUE THREAD

**Issue by xujun05** [kanjielu/jeeves#1]
jeeves可以看做itchat的java实现吗

**Comment by kanjielu** [comment]
@xujun05 jeeves本来和itchat都是参照微信web协议做的。使用微信web协议这个想法是借鉴itchat, 其他和itchat没有什么关系

**Comment by xujun05** [comment]
@kanjielu 哦，明白。你们除了wechat协议，其他并没有参考itchat。API现在稳定了吗？谢谢你的工作。

**Comment by kanjielu** [comment]
@xujun05 现有API是一个月前测试 有效的。如果你有其他需要，我可以再加

**Comment by xujun05** [comment]
@kanjielu 谢谢，我的确有所需要，希望可以为你的项目贡献代码。
