### ISSUE TITLE
如何获取微信群的名字信息？

### ISSUE THREAD

**Issue by yangboz** [kanjielu/jeeves#13]
@Override
    public void onReceivingChatRoomTextMessage(Message message) {
        logger.info("onReceivingChatRoomTextMessage");
        logger.info("from chatroom: " + message.getFromUserName());//此处得到的只是ID的字符串，并不是群的名字.

**Comment by kanjielu** [comment]
你需要通过这个ID去CacheService的chatRooms里去找这个群的详细信息。
