### ISSUE TITLE
怎么才能登录多个微信账号？

### ISSUE THREAD

**Issue by taoxiyang** [kanjielu/jeeves#9]
登录一个账号的时候服务运行得很好，登录第二个账号也能登录成功，但是过一会SyncServie.listen返回
retcode = 1102, selector = 0，两个账号都下线了，这是怎么回事？
PS: 稍稍修改了下楼主的代码，WechatHttpServiceInternal，CacheService等对象都改成每个线程一份，排除多线程问题

**Comment by taoxiyang** [comment]
已解决，不同的微信号使用不同的StatefullRestTemplate实例发送http请求

**Comment by kanjielu** [comment]
也可以启动多个Jeeves实例：）
